baseURL = 'https://sajitvasudevan.github.io'
languageCode = 'en-us'
title = 'Sajit Vasudevan'
theme = 'PaperMod'

[params]
  description = "Enterprise Architect | 25 years in technology | AWS, GxP compliance, clinical trials platforms"
  author = "Sajit Vasudevan"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sajitvasudevan/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sajitvasudevan"

[[params.socialIcons]]
  name = "medium"
  url = "https://medium.com/@sajitvasudevan"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3